var styles = {
  container: {
    flex: 1,
    //justifyContent: 'center',
    //alignItems: 'center',
    //backgroundColor: '#569fc1',
    //backgroundColor: 'rgba(40,40,54,1)',
    //backgroundColor: "rgba(2,2,25,0.2)",
    paddingTop: 30,
  },
  background: {
    height: 800,
    width: 600,
    position: 'absolute',
  },
  pagetitle: {
    fontSize: 20,
    lineHeight: 32,
    color: '#ffffff',
    textAlign: 'center',
    marginBottom: 20,
    //marginTop: '-27%',
  },
  textStyle: {
    fontSize: 16,
    textAlign: 'center',
    color: "#000"
  },
  TextInput: {
    color: '#FFF',
    height: 50,
    width: '80%',
    fontSize: 16,
    borderColor: '#cfcfcf',
    borderWidth: 1,
    borderRadius: 3,
    borderTopWidth: 0,
    borderLeftWidth: 0,
    borderRightWidth: 0,
    paddingLeft: 17,
    paddingTop: 12,
    paddingBottom: 12,
    backgroundColor: 'transparent',
  },
  View_TextInput: {
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 25,
  },
  someButtonStyle: {
    width: '70%',
    height: 50,
    backgroundColor: 'rgba(243,247,250,1)',
    borderWidth: 0,
    borderRadius: 5,
    padding: 15,
    marginTop: 30,
    alignSelf: 'center',
  },
};
export default styles;